"""add_summary_to_articles

Revision ID: 040bfead4cb8
Revises: 2b73cb0a165d
Create Date: 2026-06-15 21:51:24.004777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040bfead4cb8'
down_revision: Union[str, Sequence[str], None] = '2b73cb0a165d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'summary')
    # ### end Alembic commands ###
