"""add article timestamps

Revision ID: 598929f54a45
Revises: 889afcb91932
Create Date: 2026-06-13 12:13:56.635255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598929f54a45'
down_revision: Union[str, Sequence[str], None] = '889afcb91932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'created_at')
    op.drop_column('articles', 'published_at')
    # ### end Alembic commands ###
