APP_VERSION = "1.0.0"

API_PREFIX = "/api/v1"

DEFAULT_ARTICLE_LIMIT = 20

RSS_FETCH_INTERVAL_MINUTES = 30

EMBEDDING_MODEL = "all-MiniLM-L6-v2"
EMBEDDING_DIMENSION = 384

QDRANT_COLLECTION = "news_articles"
QDRANT_SEARCH_LIMIT = 5

SIMILARITY_THRESHOLD = 0.70

MAX_ARTICLE_INPUT_LENGTH = 8000

SUMMARY_TEMPERATURE = 0.1

GROQ_MODEL = "llama-3.1-8b-instant"

CHAT_TEMPERATURE = 0.3

MAX_RETRIEVAL_HISTORY = 3

QDRANT_SCORE_THRESHOLD = 0.60